//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_conn_H
#define METASPRITE_conn_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define conn_TILE_ORIGIN 0
#define conn_TILE_W 8
#define conn_TILE_H 8
#define conn_WIDTH 160
#define conn_HEIGHT 144
#define conn_TILE_COUNT 215
#define conn_PALETTE_COUNT 1
#define conn_COLORS_PER_PALETTE 4
#define conn_TOTAL_COLORS 4
#define conn_MAP_ATTRIBUTES 0
extern const unsigned char conn_map[360];
#define conn_map_attributes conn_map

extern const uint8_t conn_tiles[3440];

#endif
