/*

 PACHINKOONEBG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : pin.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define pachinko1Width 20
#define pachinko1Height 18
#define pachinko1Bank 0

extern unsigned char pachinko1[];

/* End of PACHINKOONEBG.H */
