//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_cas_H
#define METASPRITE_cas_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cas_TILE_ORIGIN 0
#define cas_TILE_W 8
#define cas_TILE_H 8
#define cas_WIDTH 160
#define cas_HEIGHT 144
#define cas_TILE_COUNT 256
#define cas_PALETTE_COUNT 1
#define cas_COLORS_PER_PALETTE 4
#define cas_TOTAL_COLORS 4
#define cas_MAP_ATTRIBUTES 0
extern const unsigned char cas_map[360];
#define cas_map_attributes cas_map

extern const uint8_t cas_tiles[4096];

#endif
