//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_haz_H
#define METASPRITE_haz_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define haz_TILE_ORIGIN 0
#define haz_TILE_W 8
#define haz_TILE_H 8
#define haz_WIDTH 160
#define haz_HEIGHT 144
#define haz_TILE_COUNT 255
#define haz_PALETTE_COUNT 1
#define haz_COLORS_PER_PALETTE 4
#define haz_TOTAL_COLORS 4
#define haz_MAP_ATTRIBUTES 0
extern const unsigned char haz_map[360];
#define haz_map_attributes haz_map


extern const uint8_t haz_tiles[4080];

#endif
