//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_arod_gb_H
#define METASPRITE_arod_gb_H

#define arod_gb_TILE_ORIGIN 0
#define arod_gb_TILE_W 8
#define arod_gb_TILE_H 8
#define arod_gb_WIDTH 160
#define arod_gb_HEIGHT 144
#define arod_gb_TILE_COUNT 225
#define arod_gb_PALETTE_COUNT 1
#define arod_gb_COLORS_PER_PALETTE 4
#define arod_gb_TOTAL_COLORS 4
#define arod_gb_MAP_ATTRIBUTES 0
extern const unsigned char arod_gb_map[360];
#define arod_gb_map_attributes arod_gb_map

extern const unsigned char arod_gb_tiles[3600];

#endif
