/*

 GAME1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : game_pachinko_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define game1MapWidth   20
#define game1MapHeight  18
#define game1MapBank    0
#define game1TilesBank  0

extern unsigned char game1Map[];
extern unsigned char game1Tiles[];

/* End of GAME1MAP.H */
