//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_image_H
#define METASPRITE_image_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>
#include <gb/gb.h>

#define image_TILE_ORIGIN 0
#define image_TILE_W 8
#define image_TILE_H 8
#define image_WIDTH 160
#define image_HEIGHT 144
#define image_TILE_COUNT 133
#define image_PALETTE_COUNT 1
#define image_COLORS_PER_PALETTE 4
#define image_TOTAL_COLORS 4
#define image_MAP_ATTRIBUTES 0
extern const unsigned char image_map[360];
#define image_map_attributes image_map

extern const uint8_t image_tiles[2128];

#endif
